# Simple save_and_restore

In [15]:
#### simple save _1

import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(777)

x_train = [1, 2, 3]
y_train = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

X = tf.placeholder(tf.float32, shape=[None], name="input")
Y = tf.placeholder(tf.float32, shape=[None], name="output")

hypothesis = x_train * W + b
hypothesis = tf.identity(hypothesis, "hypothesis")
cost = tf.reduce_mean(tf.square(hypothesis - y_train))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

saver = tf.train.Saver()
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(1001):
    sess.run(train)
    if(step % 100 == 0):
        print(step, sess.run(cost), sess.run(W), sess.run(b))

saver.save(sess, './my_model/my_model', global_step=1000)

0 2.823292 [2.1286771] [-0.8523567]
100 0.113226034 [1.3908179] [-0.8884077]
200 0.06996683 [1.3072149] [-0.6983712]
300 0.043235257 [1.2414987] [-0.5489836]
400 0.026716745 [1.18984] [-0.4315508]
500 0.016509337 [1.1492316] [-0.33923826]
600 0.010201736 [1.1173096] [-0.26667204]
700 0.0063040536 [1.0922159] [-0.20962858]
800 0.0038955268 [1.0724902] [-0.16478711]
900 0.0024072058 [1.056984] [-0.12953788]
1000 0.0014875027 [1.0447946] [-0.10182849]


'./my_model/my_model-1000'

In [3]:
#### simple save _2

import tensorflow as tf


tf.reset_default_graph()
tf.set_random_seed(777)

x_train = [1, 2, 3]
y_train = [1, 2, 3]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

X = tf.placeholder(tf.float32, shape=[None], name="input")
Y = tf.placeholder(tf.float32, shape=[None], name="output")

hypothesis = X * W + b
hypothesis = tf.identity(hypothesis, "hypothesis")
cost = tf.reduce_mean(tf.square(hypothesis - y_train))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

saver = tf.train.Saver()
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(1001):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict={X: x_train, Y: y_train})
    if(step % 100 == 0):
        print(step, cost_val, W_val, b_val)

saver.save(sess, './my_model/my_model', global_step=1000)




0 3.5240757 [2.1286771] [-0.8523567]
100 0.11377233 [1.3908179] [-0.8884077]
200 0.07030439 [1.3072149] [-0.6983712]
300 0.043443877 [1.2414987] [-0.5489836]
400 0.026845641 [1.18984] [-0.4315508]
500 0.016588978 [1.1492316] [-0.33923826]
600 0.010250964 [1.1173096] [-0.26667204]
700 0.0063344706 [1.0922159] [-0.20962858]
800 0.003914324 [1.0724902] [-0.16478711]
900 0.0024188235 [1.056984] [-0.12953788]
1000 0.0014946823 [1.0447946] [-0.10182849]


'./my_model/my_model-1000'

In [16]:
#### simple restore

import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(777)

sess = tf.Session()
new_saver = tf.train.import_meta_graph('my_model/my_model-1000.meta')
new_saver.restore(sess, tf.train.latest_checkpoint('./my_model'))

tf.get_default_graph()

x = sess.graph.get_tensor_by_name("input:0")
y = sess.graph.get_tensor_by_name("output:0")
hypothesis = sess.graph.get_tensor_by_name("hypothesis:0")

result = sess.run(hypothesis, feed_dict={x:[1, 2, 3]})
print(result)

#출처: https://goodtogreate.tistory.com/entry/Saving-and-Restoring [GOOD to GREAT]

INFO:tensorflow:Restoring parameters from ./my_model\my_model-1000
[0.94296604 1.9877607  3.032555  ]


In [7]:
#### simple save _3

import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(777)

W = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

X = tf.placeholder(tf.float32, shape=[None], name="input")
Y = tf.placeholder(tf.float32, shape=[None], name="output")

hypothesis = X * W + b
hypothesis = tf.identity(hypothesis, "hypothesis")
#hypothesis = sess.graph.get_tensor_by_name("hypothesis:0")

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

trainX = [1, 2, 3]
trainY = [5, 10, 15]

for step in range(1001):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict={X: trainX, Y: trainY})
    if step % 200 == 0:
        print(step, cost_val, W_val, b_val)

saver = tf.train.Saver()
save_path = saver.save(sess, 'model/simple_model')


#출처: https://lueseypid.tistory.com/248 [DevNori]

0 46.193775 [2.5020103] [-0.69235665]
200 0.00638558 [4.907413] [0.2104718]
400 0.0024383168 [4.942787] [0.1300587]
600 0.00093106297 [4.964646] [0.08036846]
800 0.0003555267 [4.9781528] [0.0496632]
1000 0.00013576442 [4.9865] [0.03068919]


In [9]:
#### simple restore _3

import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(777)

sess = tf.Session()
new_saver = tf.train.import_meta_graph('model/simple_model.meta')
new_saver.restore(sess, tf.train.latest_checkpoint('./model'))
#new_saver.restore(sess, 'model/simple_model')

tf.get_default_graph()

x = sess.graph.get_tensor_by_name("input:0")
y = sess.graph.get_tensor_by_name("output:0")
hypothesis = sess.graph.get_tensor_by_name("hypothesis:0")

result = sess.run(hypothesis, feed_dict={x:[1, 2, 3]})
print(result)


#출처: https://lueseypid.tistory.com/248 [DevNori]

INFO:tensorflow:Restoring parameters from ./model\simple_model
[ 5.017189 10.003689 14.990189]


# MNIST save_and_restore

In [5]:
# 머신러닝 학습의 Hello World 와 같은 MNIST(손글씨 숫자 인식) 문제를 신경망으로 풀어봅니다.
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# 텐서플로우에 기본 내장된 mnist 모듈을 이용하여 데이터를 로드합니다.
# 지정한 폴더에 MNIST 데이터가 없는 경우 자동으로 데이터를 다운로드합니다.
# one_hot 옵션은 레이블을 동물 분류 예제에서 보았던 one_hot 방식의 데이터로 만들어줍니다.

tf.reset_default_graph()

mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

#########
# 신경망 모델 구성
######
# 입력 값의 차원은 [배치크기, 특성값] 으로 되어 있습니다.
# 손글씨 이미지는 28x28 픽셀로 이루어져 있고, 이를 784개의 특성값으로 정합니다.
X = tf.placeholder(tf.float32, [None, 784], name='mnist_input')
# 결과는 0~9 의 10 가지 분류를 가집니다.
Y = tf.placeholder(tf.float32, [None, 10], name ='mnist_output')

# 신경망의 레이어는 다음처럼 구성합니다.
# 784(입력 특성값)
#   -> 256 (히든레이어 뉴런 갯수) -> 256 (히든레이어 뉴런 갯수)
#   -> 10 (결과값 0~9 분류)
W1 = tf.Variable(tf.random_normal([784, 256], stddev=0.01))
# 입력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L1 = tf.nn.relu(tf.matmul(X, W1))

W2 = tf.Variable(tf.random_normal([256, 256], stddev=0.01))
# L1 레이어의 출력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L2 = tf.nn.relu(tf.matmul(L1, W2))

W3 = tf.Variable(tf.random_normal([256, 10], stddev=0.01))
# 최종 모델의 출력값은 W3 변수를 곱해 10개의 분류를 가지게 됩니다.
model = tf.matmul(L2, W3)
model = tf.identity(model, "model")

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

batch_size = 100
total_batch = int(mnist.train.num_examples / batch_size)

for epoch in range(15):
    total_cost = 0

    for i in range(total_batch):
        # 텐서플로우의 mnist 모델의 next_batch 함수를 이용해
        # 지정한 크기만큼 학습할 데이터를 가져옵니다.
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)

        _, cost_val = sess.run([optimizer, cost], feed_dict={X: batch_xs, Y: batch_ys})
        total_cost += cost_val

    print('Epoch:', '%04d' % (epoch + 1),
          'Avg. cost =', '{:.3f}'.format(total_cost / total_batch))

print('최적화 완료!')

saver = tf.train.Saver()
save_path = saver.save(sess, 'model/mnist/mnist_model.ckpt')

#########
# 결과 확인
######
# model 로 예측한 값과 실제 레이블인 Y의 값을 비교합니다.
# tf.argmax 함수를 이용해 예측한 값에서 가장 큰 값을 예측한 레이블이라고 평가합니다.
# 예) [0.1 0 0 0.7 0 0.2 0 0 0 0] -> 3
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:', sess.run(accuracy,feed_dict={X: mnist.test.images,Y: mnist.test.labels}))

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 Avg. cost = 0.402
Epoch: 0002 Avg. cost = 0.145
Epoch: 0003 Avg. cost = 0.093
Epoch: 0004 Avg. cost = 0.068
Epoch: 0005 Avg. cost = 0.050
Epoch: 0006 Avg. cost = 0.039
Epoch: 0007 Avg. cost = 0.029
Epoch: 0008 Avg. cost = 0.027
Epoch: 0009 Avg. cost = 0.018
Epoch: 0010 Avg. cost = 0.019
Epoch: 0011 Avg. cost = 0.015
Epoch: 0012 Avg. cost = 0.013
Epoch: 0013 Avg. cost = 0.017
Epoch: 0014 Avg. cost = 0.011
Epoch: 0015 Avg. cost = 0.011
최적화 완료!
정확도: 0.9799


In [2]:
import pickle

f = open('images.pkl', 'wb')
pickle.dump(mnist.test.images, f)
f.close()

f = open('labels.pkl', 'wb')
pickle.dump(mnist.test.labels, f)
f.close()

f = open('images.pkl', 'rb')
image = pickle.load(f)
f.close()

f = open('labels.pkl', 'rb')
label = pickle.load(f)
f.close()

In [4]:
import tensorflow as tf
import pickle

tf.set_random_seed(777)

f = open('images.pkl', 'rb')
image = pickle.load(f)
f.close()

f = open('labels.pkl', 'rb')
label = pickle.load(f)
f.close()

sess = tf.Session()
new_saver = tf.train.import_meta_graph('model/mnist/mnist_model.ckpt.meta')
new_saver.restore(sess, 'model/mnist/mnist_model.ckpt')

tf.get_default_graph()

x = sess.graph.get_tensor_by_name("mnist_input:0")
y = sess.graph.get_tensor_by_name("mnist_output:0")
model = sess.graph.get_tensor_by_name("model:0")


is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:', sess.run(accuracy,feed_dict={x: image,y: label}))

INFO:tensorflow:Restoring parameters from model/mnist/mnist_model.ckpt
정확도: 0.9785


# RNN save_and_restore

In [ ]:
# 자연어 처리나 음성 처리 분야에 많이 사용되는 RNN 의 기본적인 사용법을 익힙니다.
# 4개의 글자를 가진 단어를 학습시켜, 3글자만 주어지면 나머지 한 글자를 추천하여 단어를 완성하는 프로그램입니다.
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

char_arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h', 'i', 'j', 'k', 'l', 'm', 'n','o', 'p', 'q', 'r', 's', 't', 'u','v', 'w', 'x', 'y', 'z']

# one-hot 인코딩 사용 및 디코딩을 하기 위해 연관 배열을 만듭니다.
# {'a': 0, 'b': 1, 'c': 2, ..., 'j': 9, 'k', 10, ...}
num_dic = {n: i for i, n in enumerate(char_arr)}
dic_len = len(num_dic)

# 다음 배열은 입력값과 출력값으로 다음처럼 사용할 것 입니다.
# wor -> X, d -> Y
# woo -> X, d -> Y
seq_data = ['word', 'wood', 'deep', 'dive', 'cold', 'cool', 'load', 'love', 'kiss', 'kind']


def make_batch(seq_data):
    input_batch = []
    target_batch = []

    for seq in seq_data:
        # 여기서 생성하는 input_batch 와 target_batch 는
        # 알파벳 배열의 인덱스 번호 입니다.
        # [22, 14, 17] [22, 14, 14] [3, 4, 4] [3, 8, 21] ...
        input = [num_dic[n] for n in seq[:-1]]
        # 3, 3, 15, 4, 3 ...
        target = num_dic[seq[-1]]
        # one-hot 인코딩을 합니다.
        # if input is [0, 1, 2]:
        # [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
        #  [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
        #  [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]
        input_batch.append(np.eye(dic_len)[input])
        # 지금까지 손실함수로 사용하던 softmax_cross_entropy_with_logits 함수는
        # label 값을 one-hot 인코딩으로 넘겨줘야 하지만,
        # 이 예제에서 사용할 손실 함수인 sparse_softmax_cross_entropy_with_logits 는
        # one-hot 인코딩을 사용하지 않으므로 index 를 그냥 넘겨주면 됩니다.
        target_batch.append(target)

    return input_batch, target_batch

#########
# 옵션 설정
######
learning_rate = 0.01
n_hidden = 128
total_epoch = 30
# 타입 스텝: [1 2 3] => 3
# RNN 을 구성하는 시퀀스의 갯수입니다.
n_step = 3
# 입력값 크기. 알파벳에 대한 one-hot 인코딩이므로 26개가 됩니다.
# 예) c => [0 0 1 0 0 0 0 0 0 0 0 ... 0]
# 출력값도 입력값과 마찬가지로 26개의 알파벳으로 분류합니다.
n_input = n_class = dic_len

#########
# 신경망 모델 구성
######
X = tf.placeholder(tf.float32, [None, n_step, n_input], name='rnn_input')
# 비용함수에 sparse_softmax_cross_entropy_with_logits 을 사용하므로
# 출력값과의 계산을 위한 원본값의 형태는 one-hot vector가 아니라 인덱스 숫자를 그대로 사용하기 때문에
# 다음처럼 하나의 값만 있는 1차원 배열을 입력값으로 받습니다.
# [3] [3] [15] [4] ...
# 기존처럼 one-hot 인코딩을 사용한다면 입력값의 형태는 [None, n_class] 여야합니다.
Y = tf.placeholder(tf.int32, [None], name='rnn_output')

W = tf.Variable(tf.random_normal([n_hidden, n_class]))
b = tf.Variable(tf.random_normal([n_class]))

# RNN 셀을 생성합니다.
cell1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
# 과적합 방지를 위한 Dropout 기법을 사용합니다.
cell1 = tf.nn.rnn_cell.DropoutWrapper(cell1, output_keep_prob=0.5)
# 여러개의 셀을 조합해서 사용하기 위해 셀을 추가로 생성합니다.
cell2 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)

# 여러개의 셀을 조합한 RNN 셀을 생성합니다.
multi_cell = tf.nn.rnn_cell.MultiRNNCell([cell1, cell2])

# tf.nn.dynamic_rnn 함수를 이용해 순환 신경망을 만듭니다.
# time_major=True
outputs, states = tf.nn.dynamic_rnn(multi_cell, X, dtype=tf.float32)

# 최종 결과는 one-hot 인코딩 형식으로 만듭니다
outputs = tf.transpose(outputs, [1, 0, 2])
outputs = outputs[-1]
model = tf.matmul(outputs, W) + b
model = tf.identity(model, 'model')
cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=model, labels=Y))

optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

#########
# 신경망 모델 학습
######
sess = tf.Session()
sess.run(tf.global_variables_initializer())

input_batch, target_batch = make_batch(seq_data)

for epoch in range(total_epoch):
    _, loss = sess.run([optimizer, cost], feed_dict={X: input_batch, Y: target_batch})

    print('Epoch:', '%04d' % (epoch + 1),
          'cost =', '{:.6f}'.format(loss))

print('최적화 완료!')

saver = tf.train.Saver()
save_path = saver.save(sess, './rnn_model.ckpt')

#########
# 결과 확인
######
# 레이블값이 정수이므로 예측값도 정수로 변경해줍니다.
prediction = tf.cast(tf.argmax(model, 1), tf.int32)
# one-hot 인코딩이 아니므로 입력값을 그대로 비교합니다.
prediction_check = tf.equal(prediction, Y)
accuracy = tf.reduce_mean(tf.cast(prediction_check, tf.float32))

input_batch, target_batch = make_batch(seq_data)

predict, accuracy_val = sess.run([prediction, accuracy],feed_dict={X: input_batch, Y: target_batch})

predict_words = []
for idx, val in enumerate(seq_data):
    last_char = char_arr[predict[idx]]
    predict_words.append(val[:3] + last_char)

print('\n=== 예측 결과 ===')
print('입력값:', [w[:3] + ' ' for w in seq_data])
print('예측값:', predict_words)
print('정확도:', accuracy_val)

In [5]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

char_arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h', 'i', 'j', 'k', 'l', 'm', 'n','o', 'p', 'q', 'r', 's', 't', 'u','v', 'w', 'x', 'y', 'z']
seq_data = ['word', 'wood', 'deep', 'dive', 'cold', 'cool', 'load', 'love', 'kiss', 'kind']
seq_data = seq_data[::-1]

num_dic = {n: i for i, n in enumerate(char_arr)}
dic_len = len(num_dic)

def make_batch(seq_data):
    input_batch = []
    target_batch = []

    for seq in seq_data:
        # 여기서 생성하는 input_batch 와 target_batch 는
        # 알파벳 배열의 인덱스 번호 입니다.
        # [22, 14, 17] [22, 14, 14] [3, 4, 4] [3, 8, 21] ...
        input = [num_dic[n] for n in seq[:-1]]
        # 3, 3, 15, 4, 3 ...
        target = num_dic[seq[-1]]
        # one-hot 인코딩을 합니다.
        # if input is [0, 1, 2]:
        # [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
        #  [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
        #  [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]
        input_batch.append(np.eye(dic_len)[input])
        # 지금까지 손실함수로 사용하던 softmax_cross_entropy_with_logits 함수는
        # label 값을 one-hot 인코딩으로 넘겨줘야 하지만,
        # 이 예제에서 사용할 손실 함수인 sparse_softmax_cross_entropy_with_logits 는
        # one-hot 인코딩을 사용하지 않으므로 index 를 그냥 넘겨주면 됩니다.
        target_batch.append(target)

    return input_batch, target_batch

sess = tf.Session()
new_saver = tf.train.import_meta_graph('./rnn_model.ckpt.meta')
new_saver.restore(sess, './rnn_model.ckpt')

tf.get_default_graph()

x = sess.graph.get_tensor_by_name("rnn_input:0")
y = sess.graph.get_tensor_by_name("rnn_output:0")
model = sess.graph.get_tensor_by_name("model:0")

#########
# 결과 확인
######
# 레이블값이 정수이므로 예측값도 정수로 변경해줍니다.
prediction = tf.cast(tf.argmax(model, 1), tf.int32)
# one-hot 인코딩이 아니므로 입력값을 그대로 비교합니다.
prediction_check = tf.equal(prediction, y)
accuracy = tf.reduce_mean(tf.cast(prediction_check, tf.float32))

input_batch, target_batch = make_batch(seq_data)

predict, accuracy_val = sess.run([prediction, accuracy],feed_dict={x: input_batch, y: target_batch})

predict_words = []
for idx, val in enumerate(seq_data):
    last_char = char_arr[predict[idx]]
    predict_words.append(val[:3] + last_char)
    
print('\n=== 예측 결과 ===')
print('입력값:', [w[:3] + ' ' for w in seq_data])
print('예측값:', predict_words)
print('정확도:', accuracy_val)

INFO:tensorflow:Restoring parameters from ./rnn_model.ckpt

=== 예측 결과 ===
입력값: ['kin ', 'kis ', 'lov ', 'loa ', 'coo ', 'col ', 'div ', 'dee ', 'woo ', 'wor ']
예측값: ['kind', 'kiss', 'love', 'load', 'cool', 'cold', 'dive', 'deep', 'wood', 'word']
정확도: 1.0


# Test

In [8]:
# tf.nn.dropout 0.8


import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# 텐서플로우에 기본 내장된 mnist 모듈을 이용하여 데이터를 로드합니다.
# 지정한 폴더에 MNIST 데이터가 없는 경우 자동으로 데이터를 다운로드합니다.
# one_hot 옵션은 레이블을 동물 분류 예제에서 보았던 one_hot 방식의 데이터로 만들어줍니다.

tf.reset_default_graph()

mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

#########
# 신경망 모델 구성
######
# 입력 값의 차원은 [배치크기, 특성값] 으로 되어 있습니다.
# 손글씨 이미지는 28x28 픽셀로 이루어져 있고, 이를 784개의 특성값으로 정합니다.
X = tf.placeholder(tf.float32, [None, 784], name='mnist_input')
# 결과는 0~9 의 10 가지 분류를 가집니다.
Y = tf.placeholder(tf.float32, [None, 10], name ='mnist_output')
keep_prob = tf.placeholder(tf.float32, name = 'mnist_keep')

# 신경망의 레이어는 다음처럼 구성합니다.
# 784(입력 특성값)
#   -> 256 (히든레이어 뉴런 갯수) -> 256 (히든레이어 뉴런 갯수)
#   -> 10 (결과값 0~9 분류)
W1 = tf.Variable(tf.random_normal([784, 256], stddev=0.01))
# 입력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L1 = tf.nn.relu(tf.matmul(X, W1))
L1 = tf.nn.dropout(L1, 0.8)

W2 = tf.Variable(tf.random_normal([256, 256], stddev=0.01))
# L1 레이어의 출력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L2 = tf.nn.relu(tf.matmul(L1, W2))
L2 = tf.nn.dropout(L2, 0.8)

W3 = tf.Variable(tf.random_normal([256, 10], stddev=0.01))
# 최종 모델의 출력값은 W3 변수를 곱해 10개의 분류를 가지게 됩니다.
model = tf.matmul(L2, W3)
model = tf.identity(model, "model")

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

batch_size = 100
total_batch = int(mnist.train.num_examples / batch_size)

for epoch in range(30):
    total_cost = 0

    for i in range(total_batch):
        # 텐서플로우의 mnist 모델의 next_batch 함수를 이용해
        # 지정한 크기만큼 학습할 데이터를 가져옵니다.
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)

        _, cost_val = sess.run([optimizer, cost], feed_dict={X: batch_xs, Y: batch_ys})
        total_cost += cost_val

    print('Epoch:', '%04d' % (epoch + 1),
          'Avg. cost =', '{:.3f}'.format(total_cost / total_batch))

print('최적화 완료!')

#########
# 결과 확인
######
# model 로 예측한 값과 실제 레이블인 Y의 값을 비교합니다.
# tf.argmax 함수를 이용해 예측한 값에서 가장 큰 값을 예측한 레이블이라고 평가합니다.
# 예) [0.1 0 0 0.7 0 0.2 0 0 0 0] -> 3
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:', sess.run(accuracy,feed_dict={X: mnist.test.images,Y: mnist.test.labels, keep_prob : 1}))

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 Avg. cost = 0.431
Epoch: 0002 Avg. cost = 0.165
Epoch: 0003 Avg. cost = 0.113
Epoch: 0004 Avg. cost = 0.091
Epoch: 0005 Avg. cost = 0.072
Epoch: 0006 Avg. cost = 0.061
Epoch: 0007 Avg. cost = 0.052
Epoch: 0008 Avg. cost = 0.046
Epoch: 0009 Avg. cost = 0.041
Epoch: 0010 Avg. cost = 0.038
Epoch: 0011 Avg. cost = 0.033
Epoch: 0012 Avg. cost = 0.031
Epoch: 0013 Avg. cost = 0.028
Epoch: 0014 Avg. cost = 0.027
Epoch: 0015 Avg. cost = 0.027
Epoch: 0016 Avg. cost = 0.025
Epoch: 0017 Avg. cost = 0.023
Epoch: 0018 Avg. cost = 0.022
Epoch: 0019 Avg. cost = 0.022
Epoch: 0020 Avg. cost = 0.021
Epoch: 0021 Avg. cost = 0.020
Epoch: 0022 Avg. cost = 0.021
Epoch: 0023 Avg. cost = 0.020
Epoch: 0024 Avg. cost = 0.017
Epoch: 0025 Avg. cost = 0.017
Epoch: 0026 Avg. cost = 0.018
Epoch: 0027 Avg. c

In [9]:
# normal 15 epoch : 98.1 , 30 epoch : 97.7
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# 텐서플로우에 기본 내장된 mnist 모듈을 이용하여 데이터를 로드합니다.
# 지정한 폴더에 MNIST 데이터가 없는 경우 자동으로 데이터를 다운로드합니다.
# one_hot 옵션은 레이블을 동물 분류 예제에서 보았던 one_hot 방식의 데이터로 만들어줍니다.

tf.reset_default_graph()

mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

#########
# 신경망 모델 구성
######
# 입력 값의 차원은 [배치크기, 특성값] 으로 되어 있습니다.
# 손글씨 이미지는 28x28 픽셀로 이루어져 있고, 이를 784개의 특성값으로 정합니다.
X = tf.placeholder(tf.float32, [None, 784], name='mnist_input')
# 결과는 0~9 의 10 가지 분류를 가집니다.
Y = tf.placeholder(tf.float32, [None, 10], name ='mnist_output')
keep_prob = tf.placeholder(tf.float32, name = 'mnist_keep')

# 신경망의 레이어는 다음처럼 구성합니다.
# 784(입력 특성값)
#   -> 256 (히든레이어 뉴런 갯수) -> 256 (히든레이어 뉴런 갯수)
#   -> 10 (결과값 0~9 분류)
W1 = tf.Variable(tf.random_normal([784, 256], stddev=0.01))
# 입력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L1 = tf.nn.relu(tf.matmul(X, W1))
#L1 = tf.nn.dropout(L1, 0.8)

W2 = tf.Variable(tf.random_normal([256, 256], stddev=0.01))
# L1 레이어의 출력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L2 = tf.nn.relu(tf.matmul(L1, W2))
#L2 = tf.nn.dropout(L2, 0.8)

W3 = tf.Variable(tf.random_normal([256, 10], stddev=0.01))
# 최종 모델의 출력값은 W3 변수를 곱해 10개의 분류를 가지게 됩니다.
model = tf.matmul(L2, W3)
model = tf.identity(model, "model")

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

batch_size = 100
total_batch = int(mnist.train.num_examples / batch_size)

for epoch in range(30):
    total_cost = 0

    for i in range(total_batch):
        # 텐서플로우의 mnist 모델의 next_batch 함수를 이용해
        # 지정한 크기만큼 학습할 데이터를 가져옵니다.
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)

        _, cost_val = sess.run([optimizer, cost], feed_dict={X: batch_xs, Y: batch_ys})
        total_cost += cost_val

    print('Epoch:', '%04d' % (epoch + 1),
          'Avg. cost =', '{:.3f}'.format(total_cost / total_batch))

print('최적화 완료!')

#########
# 결과 확인
######
# model 로 예측한 값과 실제 레이블인 Y의 값을 비교합니다.
# tf.argmax 함수를 이용해 예측한 값에서 가장 큰 값을 예측한 레이블이라고 평가합니다.
# 예) [0.1 0 0 0.7 0 0.2 0 0 0 0] -> 3
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:', sess.run(accuracy,feed_dict={X: mnist.test.images,Y: mnist.test.labels, keep_prob : 1}))

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 Avg. cost = 0.409
Epoch: 0002 Avg. cost = 0.147
Epoch: 0003 Avg. cost = 0.097
Epoch: 0004 Avg. cost = 0.070
Epoch: 0005 Avg. cost = 0.053
Epoch: 0006 Avg. cost = 0.041
Epoch: 0007 Avg. cost = 0.032
Epoch: 0008 Avg. cost = 0.025
Epoch: 0009 Avg. cost = 0.019
Epoch: 0010 Avg. cost = 0.018
Epoch: 0011 Avg. cost = 0.018
Epoch: 0012 Avg. cost = 0.013
Epoch: 0013 Avg. cost = 0.013
Epoch: 0014 Avg. cost = 0.008
Epoch: 0015 Avg. cost = 0.013
Epoch: 0016 Avg. cost = 0.012
Epoch: 0017 Avg. cost = 0.009
Epoch: 0018 Avg. cost = 0.009
Epoch: 0019 Avg. cost = 0.008
Epoch: 0020 Avg. cost = 0.006
Epoch: 0021 Avg. cost = 0.013
Epoch: 0022 Avg. cost = 0.004
Epoch: 0023 Avg. cost = 0.004
Epoch: 0024 Avg. cost = 0.014
Epoch: 0025 Avg. cost = 0.003
Epoch: 0026 Avg. cost = 0.007
Epoch: 0027 Avg. c

In [12]:
# batch_normalization
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# 텐서플로우에 기본 내장된 mnist 모듈을 이용하여 데이터를 로드합니다.
# 지정한 폴더에 MNIST 데이터가 없는 경우 자동으로 데이터를 다운로드합니다.
# one_hot 옵션은 레이블을 동물 분류 예제에서 보았던 one_hot 방식의 데이터로 만들어줍니다.

tf.reset_default_graph()

mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

#########
# 신경망 모델 구성
######
# 입력 값의 차원은 [배치크기, 특성값] 으로 되어 있습니다.
# 손글씨 이미지는 28x28 픽셀로 이루어져 있고, 이를 784개의 특성값으로 정합니다.
X = tf.placeholder(tf.float32, [None, 784], name='mnist_input')
# 결과는 0~9 의 10 가지 분류를 가집니다.
Y = tf.placeholder(tf.float32, [None, 10], name ='mnist_output')
#keep_prob = tf.placeholder(tf.float32, name = 'mnist_keep')

# 신경망의 레이어는 다음처럼 구성합니다.
# 784(입력 특성값)
#   -> 256 (히든레이어 뉴런 갯수) -> 256 (히든레이어 뉴런 갯수)
#   -> 10 (결과값 0~9 분류)
W1 = tf.Variable(tf.random_normal([784, 256], stddev=0.01))
# 입력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L1 = tf.nn.relu(tf.matmul(X, W1))
L1 = tf.layers.batch_normalization(L1)

W2 = tf.Variable(tf.random_normal([256, 256], stddev=0.01))
# L1 레이어의 출력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L2 = tf.nn.relu(tf.matmul(L1, W2))
L2 = tf.layers.batch_normalization(L2)

W3 = tf.Variable(tf.random_normal([256, 10], stddev=0.01))
# 최종 모델의 출력값은 W3 변수를 곱해 10개의 분류를 가지게 됩니다.
model = tf.matmul(L2, W3)
model = tf.identity(model, "model")

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

batch_size = 100
total_batch = int(mnist.train.num_examples / batch_size)

for epoch in range(30):
    total_cost = 0

    for i in range(total_batch):
        # 텐서플로우의 mnist 모델의 next_batch 함수를 이용해
        # 지정한 크기만큼 학습할 데이터를 가져옵니다.
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)

        _, cost_val = sess.run([optimizer, cost], feed_dict={X: batch_xs, Y: batch_ys})
        total_cost += cost_val

    print('Epoch:', '%04d' % (epoch + 1),
          'Avg. cost =', '{:.3f}'.format(total_cost / total_batch))

print('최적화 완료!')

#########
# 결과 확인
######
# model 로 예측한 값과 실제 레이블인 Y의 값을 비교합니다.
# tf.argmax 함수를 이용해 예측한 값에서 가장 큰 값을 예측한 레이블이라고 평가합니다.
# 예) [0.1 0 0 0.7 0 0.2 0 0 0 0] -> 3
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:', sess.run(accuracy,feed_dict={X: mnist.test.images,Y: mnist.test.labels}))

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 Avg. cost = 0.399
Epoch: 0002 Avg. cost = 0.142
Epoch: 0003 Avg. cost = 0.091
Epoch: 0004 Avg. cost = 0.067
Epoch: 0005 Avg. cost = 0.051
Epoch: 0006 Avg. cost = 0.039
Epoch: 0007 Avg. cost = 0.028
Epoch: 0008 Avg. cost = 0.026
Epoch: 0009 Avg. cost = 0.022
Epoch: 0010 Avg. cost = 0.017
Epoch: 0011 Avg. cost = 0.014
Epoch: 0012 Avg. cost = 0.014
Epoch: 0013 Avg. cost = 0.011
Epoch: 0014 Avg. cost = 0.014
Epoch: 0015 Avg. cost = 0.008
Epoch: 0016 Avg. cost = 0.014
Epoch: 0017 Avg. cost = 0.007
Epoch: 0018 Avg. cost = 0.010
Epoch: 0019 Avg. cost = 0.010
Epoch: 0020 Avg. cost = 0.008
Epoch: 0021 Avg. cost = 0.006
Epoch: 0022 Avg. cost = 0.009
Epoch: 0023 Avg. cost = 0.006
Epoch: 0024 Avg. cost = 0.006
Epoch: 0025 Avg. cost = 0.008
Epoch: 0026 Avg. cost = 0.005
Epoch: 0027 Avg. c

In [ ]:
# batch_normalization
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# 텐서플로우에 기본 내장된 mnist 모듈을 이용하여 데이터를 로드합니다.
# 지정한 폴더에 MNIST 데이터가 없는 경우 자동으로 데이터를 다운로드합니다.
# one_hot 옵션은 레이블을 동물 분류 예제에서 보았던 one_hot 방식의 데이터로 만들어줍니다.

tf.reset_default_graph()

mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

#########
# 신경망 모델 구성
######
# 입력 값의 차원은 [배치크기, 특성값] 으로 되어 있습니다.
# 손글씨 이미지는 28x28 픽셀로 이루어져 있고, 이를 784개의 특성값으로 정합니다.
X = tf.placeholder(tf.float32, [None, 784], name='mnist_input')
# 결과는 0~9 의 10 가지 분류를 가집니다.
Y = tf.placeholder(tf.float32, [None, 10], name ='mnist_output')
#keep_prob = tf.placeholder(tf.float32, name = 'mnist_keep')

# 신경망의 레이어는 다음처럼 구성합니다.
# 784(입력 특성값)
#   -> 256 (히든레이어 뉴런 갯수) -> 256 (히든레이어 뉴런 갯수)
#   -> 10 (결과값 0~9 분류)
W1 = tf.Variable(tf.random_normal([784, 256], stddev=0.01))
# 입력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L1 = tf.nn.relu(tf.matmul(X, W1))
L1 = tf.layers.batch_normalization(L1)

W2 = tf.Variable(tf.random_normal([256, 256], stddev=0.01))
# L1 레이어의 출력값에 가중치를 곱하고 ReLU 함수를 이용하여 레이어를 만듭니다.
L2 = tf.nn.relu(tf.matmul(L1, W2))
L2 = tf.layers.batch_normalization(L2)

W3 = tf.Variable(tf.random_normal([256, 10], stddev=0.01))
# 최종 모델의 출력값은 W3 변수를 곱해 10개의 분류를 가지게 됩니다.
model = tf.matmul(L2, W3)
model = tf.identity(model, "model")

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

batch_size = 100
total_batch = int(mnist.train.num_examples / batch_size)

for epoch in range(15):
    total_cost = 0

    for i in range(total_batch):
        # 텐서플로우의 mnist 모델의 next_batch 함수를 이용해
        # 지정한 크기만큼 학습할 데이터를 가져옵니다.
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)

        _, cost_val = sess.run([optimizer, cost], feed_dict={X: batch_xs, Y: batch_ys})
        total_cost += cost_val

    print('Epoch:', '%04d' % (epoch + 1),
          'Avg. cost =', '{:.3f}'.format(total_cost / total_batch))

print('최적화 완료!')

#########
# 결과 확인
######
# model 로 예측한 값과 실제 레이블인 Y의 값을 비교합니다.
# tf.argmax 함수를 이용해 예측한 값에서 가장 큰 값을 예측한 레이블이라고 평가합니다.
# 예) [0.1 0 0 0.7 0 0.2 0 0 0 0] -> 3
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:', sess.run(accuracy,feed_dict={X: mnist.test.images,Y: mnist.test.labels}))

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 Avg. cost = 0.403
Epoch: 0002 Avg. cost = 0.144
Epoch: 0003 Avg. cost = 0.094
Epoch: 0004 Avg. cost = 0.068
Epoch: 0005 Avg. cost = 0.049
Epoch: 0006 Avg. cost = 0.038
Epoch: 0007 Avg. cost = 0.031
Epoch: 0008 Avg. cost = 0.024
Epoch: 0009 Avg. cost = 0.020
Epoch: 0010 Avg. cost = 0.020
Epoch: 0011 Avg. cost = 0.013
